# Generated by Django 3.1.1 on 2021-07-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('folio', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('firmaCli', models.CharField(max_length=20)),
                ('firmaEmp', models.CharField(max_length=20)),
            ],
        ),
    ]
