# Generated by Django 3.1.1 on 2021-07-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNomas', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=50),
        ),
    ]
